import json
import time
from playwright.sync_api import sync_playwright

ROOT_URL = "https://gofile.io/d/OBVVp1LI"
ROOT_FOLDER_ID = "OBVVp1LI"

def scrape_as_real_user():
    print("🌐 Launching Chromium browser session...")
    
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu"
            ]
        )
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
            viewport={"width": 1280, "height": 800}
        )
        page = context.new_page()

        print("📄 Navigating to Gofile root folder...")
        page.goto(ROOT_URL, wait_until="networkidle", timeout=60000)
        page.wait_for_timeout(4000)

        # Extract guest tokens, cookies, and site tokens generated by Gofile's frontend
        auth_data = page.evaluate("""() => {
            let token = localStorage.getItem('accountToken') || localStorage.getItem('token') || '';
            let wt = localStorage.getItem('websiteToken') || '';
            return {
                token: token,
                websiteToken: wt,
                cookie: document.cookie || ''
            };
        }""")

        cookies = context.cookies()
        cookie_header = "; ".join([f"{c['name']}={c['value']}" for c in cookies])
        if not auth_data["cookie"]:
            auth_data["cookie"] = cookie_header

        print(f"🔑 Captured session auth (Token present: {bool(auth_data['token'])})")

        # Recursively crawl ALL folders and files using native browser fetch within the active session
        print("📂 Crawling all folder directories and items...")
        files = page.evaluate("""async (rootId) => {
            let visited = new Set();
            let queue = [rootId];
            let allItems = [];
            let token = localStorage.getItem('accountToken') || localStorage.getItem('token') || '';

            while (queue.length > 0) {
                let currentId = queue.shift();
                if (visited.has(currentId)) continue;
                visited.add(currentId);

                let pageNum = 1;
                while (true) {
                    let url = `https://api.gofile.io/contents/${currentId}?page=${pageNum}&pageSize=1000&sortField=createTime&sortDirection=-1`;
                    try {
                        let res = await fetch(url, {
                            headers: token ? { 'Authorization': 'Bearer ' + token } : {}
                        });
                        let json = await res.json();
                        if (json.status !== 'ok' || !json.data || !json.data.children) break;

                        let children = json.data.children;
                        let countOnPage = 0;

                        for (let id in children) {
                            countOnPage++;
                            let item = children[id];
                            if (item.type === 'folder') {
                                let code = item.code || item.id || id;
                                if (!visited.has(code) && !queue.includes(code)) {
                                    queue.push(code);
                                }
                            } else {
                                let dlUrl = item.link || item.directDownload || item.downloadPage || '';
                                if (dlUrl) {
                                    allItems.push({
                                        id: 'gofile:' + id,
                                        item_id: id,
                                        name: item.name || 'Untitled',
                                        url: dlUrl,
                                        size: item.size ? (item.size / (1024 * 1024)).toFixed(2) + ' MB' : 'Unknown'
                                    });
                                }
                            }
                        }

                        // Stop if empty or if we have traversed the total pages
                        if (countOnPage === 0 || pageNum >= (json.data.totalChildrenPages || 1)) break;
                        pageNum++;
                    } catch (e) {
                        break;
                    }
                }
            }
            return allItems;
        }""", ROOT_FOLDER_ID)

        browser.close()

    print(f"🎉 Crawl finished: Found {len(files)} total files.")

    output = {
        "auth": auth_data,
        "files": files,
        "updated_at": int(time.time())
    }

    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

if __name__ == "__main__":
    scrape_as_real_user()
